services:
  SensioLabs\Consul\ServiceFactory:
    arguments:
      - {'base_uri': '%consul.agent.base_uri%'}

  SensioLabs\Consul\Services\Agent:
    factory: ['@SensioLabs\Consul\ServiceFactory', 'get']
    arguments: ['SensioLabs\Consul\Services\AgentInterface']

  Akondas\ConsulBundle\Service\ConsulAgent:
    class: 'Akondas\ConsulBundle\Service\ConsulAgent\SensioLabsConsulAgent'
    arguments:
      - '@SensioLabs\Consul\Services\Agent'
      - '@router.default'

  Akondas\ConsulBundle\Command\RegisterServiceCommand:
    arguments:
      - '@Akondas\ConsulBundle\Service\ConsulAgent'
      - '%consul.service.name%'
      - '%consul.service.host%'
      - '%consul.service.port%'
    tags: ['console.command']

  Akondas\ConsulBundle\Command\DeregisterServiceCommand:
    arguments:
      - '@Akondas\ConsulBundle\Service\ConsulAgent'
      - '%consul.service.name%'
    tags: ['console.command']

  Akondas\ConsulBundle\Command\DebugCheckCommand:
    arguments:
      - '@Akondas\ConsulBundle\Service\ConsulAgent'
      - '%consul.service.name%'
    tags: ['console.command']

  Akondas\ConsulBundle\Controller\HealthController:
    tags: ['controller.service_arguments']
